"""向管理平面公开的内置配置定义。"""

from collections.abc import Iterable

from cnb_adapters import AlertWebhookValidationError, validate_webhook_url
from cnb_application.alert_policy import ALERT_NOTIFICATION_ADAPTERS
from cnb_domain import ConfigDefinition, ConfigEntry, ConfigScope, ConfigValueKind, JsonValue


class ConfigurationValidationError(ValueError):
    """配置值不符合已注册定义时抛出。"""


class ConfigurationRegistry:
    """带类型运行配置定义的不可变注册表。"""

    def __init__(self, definitions: Iterable[ConfigDefinition]) -> None:
        by_key: dict[str, ConfigDefinition] = {}
        for definition in definitions:
            if definition.key in by_key:
                raise ValueError(f"存在重复配置键：{definition.key}")
            by_key[definition.key] = definition
        self._definitions = by_key

    def all(self) -> tuple[ConfigDefinition, ...]:
        """按稳定的分区和配置键顺序返回定义。"""
        return tuple(sorted(self._definitions.values(), key=lambda item: (item.section, item.key)))

    def get(self, key: str) -> ConfigDefinition:
        """返回单个定义，未知配置键继续抛出 KeyError。"""
        return self._definitions[key]

    def __len__(self) -> int:
        return len(self._definitions)

    def validate_entry(self, entry: ConfigEntry) -> None:
        """校验值类型、作用域以及数值或选项约束。"""
        try:
            definition = self.get(entry.key)
        except KeyError as error:
            raise ConfigurationValidationError(f"未知配置键：{entry.key}") from error

        if definition.secret:
            raise ConfigurationValidationError(f"密钥配置必须通过密钥存储处理：{entry.key}")
        if entry.scope_type not in definition.scopes:
            raise ConfigurationValidationError(
                f"配置 {entry.key} 不支持作用域 {entry.scope_type.value}"
            )
        if entry.scope_type is ConfigScope.SYSTEM and entry.scope_id is not None:
            raise ConfigurationValidationError("系统作用域不能设置作用域 ID")
        if entry.scope_type is not ConfigScope.SYSTEM and entry.scope_id is None:
            raise ConfigurationValidationError(f"作用域 {entry.scope_type.value} 必须设置作用域 ID")

        self._validate_value(definition, entry.value)

    @staticmethod
    def _validate_value(definition: ConfigDefinition, value: JsonValue) -> None:
        expected = definition.value_kind
        valid = False
        if expected is ConfigValueKind.STRING:
            valid = isinstance(value, str)
        elif expected is ConfigValueKind.BOOLEAN:
            valid = isinstance(value, bool)
        elif expected is ConfigValueKind.INTEGER:
            valid = isinstance(value, int) and not isinstance(value, bool)
        elif expected is ConfigValueKind.NUMBER:
            valid = isinstance(value, (int, float)) and not isinstance(value, bool)
        elif expected is ConfigValueKind.STRING_LIST:
            valid = isinstance(value, list) and all(isinstance(item, str) for item in value)

        if not valid:
            raise ConfigurationValidationError(
                f"配置 {definition.key} 的值不符合 {expected.value} 类型"
            )

        if isinstance(value, (int, float)) and not isinstance(value, bool):
            if definition.minimum is not None and value < definition.minimum:
                raise ConfigurationValidationError(
                    f"配置 {definition.key} 不能小于 {definition.minimum}"
                )
            if definition.maximum is not None and value > definition.maximum:
                raise ConfigurationValidationError(
                    f"配置 {definition.key} 不能大于 {definition.maximum}"
                )
        if definition.options and value not in definition.options:
            raise ConfigurationValidationError(
                f"配置 {definition.key} 必须是以下选项之一：{', '.join(definition.options)}"
            )
        if (
            definition.key
            in {
                "alerts.notification.webhook_url",
                "alerts.notification.feishu_webhook_url",
            }
            and isinstance(value, str)
            and value
        ):
            try:
                validate_webhook_url(value)
            except AlertWebhookValidationError as error:
                raise ConfigurationValidationError(str(error)) from error


def build_default_registry() -> ConfigurationRegistry:
    """创建持久化覆盖值生效前使用的安全内置基线。"""
    system_and_tenant = (ConfigScope.SYSTEM, ConfigScope.TENANT)
    per_agent = (*system_and_tenant, ConfigScope.AGENT)
    per_channel = (*per_agent, ConfigScope.CHANNEL)
    all_scopes = (*per_channel, ConfigScope.USER)

    return ConfigurationRegistry(
        (
            ConfigDefinition(
                key="system.default_timezone",
                section="system",
                label="默认时区",
                description="智能体在没有用户级时区时使用的 IANA 时区。",
                value_kind=ConfigValueKind.STRING,
                default="Asia/Shanghai",
                scopes=(*system_and_tenant, ConfigScope.USER),
            ),
            ConfigDefinition(
                key="cognition.context.max_tokens",
                section="cognition",
                label="上下文 Token 上限",
                description="单次认知运行在模型调用前允许组装的最大上下文预算。",
                value_kind=ConfigValueKind.INTEGER,
                default=24000,
                scopes=per_agent,
                minimum=2048,
                maximum=200000,
            ),
            ConfigDefinition(
                key="cognition.context.summary_enabled",
                section="cognition",
                label="启用长对话分层摘要",
                description="将最近窗口之外的较早消息压缩为不可信历史背景，避免长会话突然失忆。",
                value_kind=ConfigValueKind.BOOLEAN,
                default=True,
                scopes=per_agent,
            ),
            ConfigDefinition(
                key="cognition.context.source_message_limit",
                section="cognition",
                label="上下文历史读取上限",
                description="每次运行最多从会话真相源读取多少条消息用于最近上下文和分层摘要。",
                value_kind=ConfigValueKind.INTEGER,
                default=240,
                scopes=per_agent,
                minimum=40,
                maximum=2000,
            ),
            ConfigDefinition(
                key="cognition.context.recent_message_limit",
                section="cognition",
                label="最近消息保留数量",
                description="分层压缩前保持逐条原文的最近消息数量，当前触发消息始终作为必需上下文。",
                value_kind=ConfigValueKind.INTEGER,
                default=24,
                scopes=per_agent,
                minimum=4,
                maximum=200,
            ),
            ConfigDefinition(
                key="cognition.context.summary_chunk_size",
                section="cognition",
                label="长对话摘要分块大小",
                description="每个摘要节点聚合的消息或下层摘要数量。",
                value_kind=ConfigValueKind.INTEGER,
                default=8,
                scopes=per_agent,
                minimum=2,
                maximum=64,
            ),
            ConfigDefinition(
                key="cognition.context.summary_max_levels",
                section="cognition",
                label="长对话摘要最大层级",
                description="摘要超出独立预算时允许继续聚合的最大层级。",
                value_kind=ConfigValueKind.INTEGER,
                default=4,
                scopes=per_agent,
                minimum=1,
                maximum=8,
            ),
            ConfigDefinition(
                key="cognition.context.summary_token_budget",
                section="cognition",
                label="长对话摘要 Token 预算",
                description="较早对话摘要在全局上下文预算内可使用的独立 Token 上限。",
                value_kind=ConfigValueKind.INTEGER,
                default=4096,
                scopes=per_agent,
                minimum=128,
                maximum=64000,
            ),
            ConfigDefinition(
                key="cognition.affect.half_life_seconds",
                section="cognition",
                label="短期情绪半衰期",
                description="短期情绪状态回归中性基线所需的秒数。",
                value_kind=ConfigValueKind.INTEGER,
                default=21600,
                scopes=per_agent,
                minimum=60,
                maximum=604800,
            ),
            ConfigDefinition(
                key="cognition.reflection.enabled",
                section="cognition",
                label="启用异步反思",
                description="在对话完成后生成 Episode、记忆和关系更新候选。",
                value_kind=ConfigValueKind.BOOLEAN,
                default=True,
                scopes=per_agent,
            ),
            ConfigDefinition(
                key="cognition.reflection.delay_seconds",
                section="cognition",
                label="异步反思延迟",
                description="对话运行结束后等待多少秒再执行反思，避免与前台响应争抢资源。",
                value_kind=ConfigValueKind.INTEGER,
                default=3,
                scopes=per_agent,
                minimum=0,
                maximum=3600,
            ),
            ConfigDefinition(
                key="cognition.reflection.minimum_importance",
                section="cognition",
                label="反思记忆最低重要性",
                description="异步反思候选达到该重要性后才写入长期情景记忆。",
                value_kind=ConfigValueKind.NUMBER,
                default=0.45,
                scopes=per_agent,
                minimum=0,
                maximum=1,
            ),
            ConfigDefinition(
                key="cognition.reflection.memory_write_mode",
                section="cognition",
                label="反思记忆写入策略",
                description="高精度模式只保留明确的稳定信息；均衡模式还允许较完整的自我披露形成未确认情景记忆。",
                value_kind=ConfigValueKind.STRING,
                default="high_precision",
                scopes=per_agent,
                options=("high_precision", "balanced"),
            ),
            ConfigDefinition(
                key="cognition.reflection.relationship_positive_step",
                section="cognition",
                label="关系正向变化步长",
                description="感谢、友好和谨慎自我披露每次最多带来的亲和度或信任度变化。",
                value_kind=ConfigValueKind.NUMBER,
                default=0.02,
                scopes=per_agent,
                minimum=0,
                maximum=0.2,
            ),
            ConfigDefinition(
                key="cognition.reflection.relationship_negative_step",
                section="cognition",
                label="关系负向变化步长",
                description="明确敌意或持续纠错每次最多带来的亲和度或信任度回落。",
                value_kind=ConfigValueKind.NUMBER,
                default=0.04,
                scopes=per_agent,
                minimum=0,
                maximum=0.2,
            ),
            ConfigDefinition(
                key="cognition.reflection.familiarity_step",
                section="cognition",
                label="关系熟悉度变化步长",
                description="一次有效互动带来的熟悉度基准增量；寒暄、普通提问和敌意会自动降低增量。",
                value_kind=ConfigValueKind.NUMBER,
                default=0.015,
                scopes=per_agent,
                minimum=0,
                maximum=0.2,
            ),
            ConfigDefinition(
                key="evaluation.comparison.max_candidates",
                section="evaluation",
                label="单次模型对比候选上限",
                description="同一评测快照允许并列回放的最大已发布模型档案数量。",
                value_kind=ConfigValueKind.INTEGER,
                default=4,
                scopes=per_agent,
                minimum=2,
                maximum=8,
            ),
            ConfigDefinition(
                key="tasks.max_attempts",
                section="tasks",
                label="任务最大尝试次数",
                description="后台任务进入死信前允许的执行尝试总数。",
                value_kind=ConfigValueKind.INTEGER,
                default=5,
                scopes=system_and_tenant,
                minimum=1,
                maximum=20,
            ),
            ConfigDefinition(
                key="tasks.lease_seconds",
                section="tasks",
                label="任务执行租约",
                description="任务进程认领任务后的租约秒数；过期后由恢复器接管。",
                value_kind=ConfigValueKind.INTEGER,
                default=120,
                scopes=system_and_tenant,
                minimum=5,
                maximum=3600,
            ),
            ConfigDefinition(
                key="tasks.retry_base_seconds",
                section="tasks",
                label="失败退避基数",
                description="任务与事务发件箱发布失败后指数退避的起始秒数。",
                value_kind=ConfigValueKind.INTEGER,
                default=5,
                scopes=system_and_tenant,
                minimum=1,
                maximum=600,
            ),
            ConfigDefinition(
                key="inbox.max_payload_bytes",
                section="inbox",
                label="入站载荷大小上限",
                description="签名验证后的原始事件允许进入规范化流程的最大字节数。",
                value_kind=ConfigValueKind.INTEGER,
                default=1024 * 1024,
                scopes=per_channel,
                minimum=1024,
                maximum=10 * 1024 * 1024,
            ),
            ConfigDefinition(
                key="inbox.max_event_age_seconds",
                section="inbox",
                label="入站事件最大时差",
                description="平台事件时间与本地接收时间允许相差的最大秒数。",
                value_kind=ConfigValueKind.INTEGER,
                default=300,
                scopes=per_channel,
                minimum=1,
                maximum=86400,
            ),
            ConfigDefinition(
                key="inbox.max_attempts",
                section="inbox",
                label="入站任务最大尝试次数",
                description="净化后的事件信封进入死信前允许的后台处理次数。",
                value_kind=ConfigValueKind.INTEGER,
                default=5,
                scopes=per_channel,
                minimum=1,
                maximum=20,
            ),
            ConfigDefinition(
                key="inbox.replay_enabled",
                section="inbox",
                label="允许入站箱安全重放",
                description="允许管理员从已净化事件信封创建新任务，不重新接收原始载荷。",
                value_kind=ConfigValueKind.BOOLEAN,
                default=True,
                scopes=per_channel,
            ),
            ConfigDefinition(
                key="observability.window_minutes",
                section="observability",
                label="可观测聚合窗口",
                description="SLO、模型成本和活动告警聚合最近多少分钟的数据。",
                value_kind=ConfigValueKind.INTEGER,
                default=60,
                scopes=system_and_tenant,
                minimum=5,
                maximum=10080,
            ),
            ConfigDefinition(
                key="alerts.baseline.window_minutes",
                section="observability",
                label="告警基线与交接窗口",
                description="异常基线当前周期和值班交接摘要覆盖的分钟数。",
                value_kind=ConfigValueKind.INTEGER,
                default=480,
                scopes=system_and_tenant,
                minimum=60,
                maximum=10_080,
            ),
            ConfigDefinition(
                key="alerts.baseline.periods",
                section="observability",
                label="告警基线历史周期数",
                description="计算中位数与 MAD 稳健基线使用的前置等长周期数。",
                value_kind=ConfigValueKind.INTEGER,
                default=7,
                scopes=system_and_tenant,
                minimum=3,
                maximum=30,
            ),
            ConfigDefinition(
                key="alerts.baseline.sensitivity",
                section="observability",
                label="告警基线异常灵敏度",
                description="异常阈值高于历史中位数的稳健离散倍数，越高越保守。",
                value_kind=ConfigValueKind.NUMBER,
                default=3.0,
                scopes=system_and_tenant,
                minimum=1.0,
                maximum=10.0,
            ),
            ConfigDefinition(
                key="alerts.baseline.minimum_current_count",
                section="observability",
                label="告警基线最小当前事件数",
                description="当前窗口至少达到该数量才会标记为基线异常。",
                value_kind=ConfigValueKind.INTEGER,
                default=3,
                scopes=system_and_tenant,
                minimum=1,
                maximum=10_000,
            ),
            ConfigDefinition(
                key="alerts.recommendation.long_running_minutes",
                section="observability",
                label="告警建议长时间阈值",
                description="活动告警持续达到该分钟数后，处置建议将提升为人工确认并调查。",
                value_kind=ConfigValueKind.INTEGER,
                default=120,
                scopes=system_and_tenant,
                minimum=5,
                maximum=525_600,
            ),
            ConfigDefinition(
                key="alerts.recommendation.suppression_minutes",
                section="observability",
                label="告警建议临时抑制时长",
                description="普通重复警告经人工确认后建议使用的临时抑制分钟数。",
                value_kind=ConfigValueKind.INTEGER,
                default=60,
                scopes=system_and_tenant,
                minimum=5,
                maximum=10_080,
            ),
            ConfigDefinition(
                key="alerts.recommendation.minimum_repeated_occurrences",
                section="observability",
                label="告警建议最小重复次数",
                description="普通警告至少重复达到该次数后才建议人工临时抑制。",
                value_kind=ConfigValueKind.INTEGER,
                default=3,
                scopes=system_and_tenant,
                minimum=2,
                maximum=10_000,
            ),
            ConfigDefinition(
                key="slo.api.maximum_error_rate_percent",
                section="observability",
                label="应用接口最大错误率",
                description="当前聚合窗口允许的服务端错误请求比例上限。",
                value_kind=ConfigValueKind.NUMBER,
                default=1.0,
                scopes=system_and_tenant,
                minimum=0,
                maximum=100,
            ),
            ConfigDefinition(
                key="slo.api.maximum_p95_ms",
                section="observability",
                label="应用接口 P95 延迟上限",
                description="当前聚合窗口应用接口 P95 响应时间的毫秒上限。",
                value_kind=ConfigValueKind.INTEGER,
                default=500,
                scopes=system_and_tenant,
                minimum=1,
                maximum=600000,
            ),
            ConfigDefinition(
                key="slo.agent.minimum_success_rate_percent",
                section="observability",
                label="智能体运行最低成功率",
                description="当前聚合窗口内智能体运行正常完成比例的下限。",
                value_kind=ConfigValueKind.NUMBER,
                default=99.0,
                scopes=system_and_tenant,
                minimum=0,
                maximum=100,
            ),
            ConfigDefinition(
                key="slo.agent.maximum_p95_ms",
                section="observability",
                label="智能体运行 P95 延迟上限",
                description="当前聚合窗口内智能体运行从开始到终态的 P95 毫秒上限。",
                value_kind=ConfigValueKind.INTEGER,
                default=15000,
                scopes=system_and_tenant,
                minimum=1,
                maximum=3600000,
            ),
            ConfigDefinition(
                key="alerts.queue.maximum_backlog",
                section="observability",
                label="队列积压告警阈值",
                description="待处理与重试后台任务数量允许的上限。",
                value_kind=ConfigValueKind.INTEGER,
                default=100,
                scopes=system_and_tenant,
                minimum=0,
                maximum=1000000,
            ),
            ConfigDefinition(
                key="alerts.model.maximum_failure_rate_percent",
                section="observability",
                label="模型调用最大失败率",
                description="当前窗口全部模型尝试允许的失败与超时比例上限。",
                value_kind=ConfigValueKind.NUMBER,
                default=5.0,
                scopes=system_and_tenant,
                minimum=0,
                maximum=100,
            ),
            ConfigDefinition(
                key="alerts.queue.maximum_oldest_wait_seconds",
                section="observability",
                label="最老任务等待阈值",
                description="最早可执行后台任务允许等待的秒数上限。",
                value_kind=ConfigValueKind.INTEGER,
                default=300,
                scopes=system_and_tenant,
                minimum=0,
                maximum=604800,
            ),
            ConfigDefinition(
                key="alerts.channel.enabled",
                section="observability",
                label="启用渠道告警",
                description="根据安全错误聚合和健康快照生成渠道活动告警。",
                value_kind=ConfigValueKind.BOOLEAN,
                default=True,
                scopes=system_and_tenant,
            ),
            ConfigDefinition(
                key="alerts.channel.enabled_error_codes",
                section="observability",
                label="渠道告警错误码",
                description="允许触发告警的安全错误码；星号表示全部错误码。",
                value_kind=ConfigValueKind.STRING_LIST,
                default=["*"],
                scopes=system_and_tenant,
            ),
            ConfigDefinition(
                key="alerts.channel.minimum_severity",
                section="observability",
                label="渠道最低告警级别",
                description="低于该严重级别的渠道活动告警不在管理后台显示。",
                value_kind=ConfigValueKind.STRING,
                default="warning",
                scopes=system_and_tenant,
                options=("warning", "critical"),
            ),
            ConfigDefinition(
                key="alerts.channel.cooldown_minutes",
                section="observability",
                label="渠道告警冷却时间",
                description="相同渠道和告警类型合并为单条结果时使用的冷却分钟数。",
                value_kind=ConfigValueKind.INTEGER,
                default=15,
                scopes=system_and_tenant,
                minimum=1,
                maximum=1440,
            ),
            ConfigDefinition(
                key="alerts.channel.failure_rate_percent",
                section="observability",
                label="渠道失败率阈值",
                description="当前窗口出站失败和限流占已完成尝试的百分比告警阈值。",
                value_kind=ConfigValueKind.NUMBER,
                default=5.0,
                scopes=system_and_tenant,
                minimum=0,
                maximum=100,
            ),
            ConfigDefinition(
                key="alerts.channel.health_degraded_minutes",
                section="observability",
                label="渠道持续降级阈值",
                description="最近健康快照连续处于降级状态达到该分钟数后告警。",
                value_kind=ConfigValueKind.INTEGER,
                default=5,
                scopes=system_and_tenant,
                minimum=1,
                maximum=10080,
            ),
            ConfigDefinition(
                key="alerts.notification.adapter",
                section="observability",
                label="告警通知适配器",
                description="选择告警摘要的投递协议。",
                value_kind=ConfigValueKind.STRING,
                default="webhook",
                scopes=per_agent,
                options=("webhook", "feishu_webhook", "email"),
            ),
            ConfigDefinition(
                key="alerts.notification.enabled",
                section="observability",
                label="启用告警 Webhook 通知",
                description="将当前 Agent 的安全告警摘要投递到 HTTPS Webhook，默认关闭。",
                value_kind=ConfigValueKind.BOOLEAN,
                default=False,
                scopes=per_agent,
            ),
            ConfigDefinition(
                key="alerts.notification.recovery_enabled",
                section="observability",
                label="启用告警恢复通知",
                description="此前已成功通知的活动告警全部恢复后，自动且仅一次投递恢复摘要。",
                value_kind=ConfigValueKind.BOOLEAN,
                default=True,
                scopes=per_agent,
            ),
            ConfigDefinition(
                key="alerts.notification.escalation_enabled",
                section="observability",
                label="启用持续告警升级",
                description="活动告警持续超过阈值后，通过可靠任务额外投递一次升级通知。",
                value_kind=ConfigValueKind.BOOLEAN,
                default=True,
                scopes=per_agent,
            ),
            ConfigDefinition(
                key="alerts.notification.escalation_after_minutes",
                section="observability",
                label="告警升级等待时间",
                description="活动告警首次发生后等待多少分钟触发一次幂等升级通知。",
                value_kind=ConfigValueKind.INTEGER,
                default=30,
                scopes=per_agent,
                minimum=1,
                maximum=10_080,
            ),
            ConfigDefinition(
                key="alerts.notification.escalation_level_2_after_minutes",
                section="observability",
                label="二级升级等待时间",
                description="活动告警首次发生后达到二级升级所需的持续分钟数。",
                value_kind=ConfigValueKind.INTEGER,
                default=120,
                scopes=per_agent,
                minimum=1,
                maximum=10_080,
            ),
            ConfigDefinition(
                key="alerts.notification.escalation_level_3_after_minutes",
                section="observability",
                label="三级升级等待时间",
                description="活动告警首次发生后达到三级升级所需的持续分钟数。",
                value_kind=ConfigValueKind.INTEGER,
                default=360,
                scopes=per_agent,
                minimum=1,
                maximum=10_080,
            ),
            *(
                ConfigDefinition(
                    key=f"alerts.notification.escalation_level_{level}_adapter",
                    section="observability",
                    label=f"{label}升级通知适配器",
                    description="值班时段内该升级等级使用的通知适配器；默认表示继承主适配器。",
                    value_kind=ConfigValueKind.STRING,
                    default="default",
                    scopes=per_agent,
                    options=("default", *ALERT_NOTIFICATION_ADAPTERS),
                )
                for level, label in ((1, "一级"), (2, "二级"), (3, "三级"))
            ),
            ConfigDefinition(
                key="alerts.notification.warning_max_escalation_level",
                section="observability",
                label="警告最高升级等级",
                description="warning 告警允许达到的最高等级；0 表示不升级 warning 告警。",
                value_kind=ConfigValueKind.INTEGER,
                default=1,
                scopes=per_agent,
                minimum=0,
                maximum=3,
            ),
            ConfigDefinition(
                key="alerts.notification.on_call_timezone",
                section="observability",
                label="告警值班时区",
                description="使用 IANA 时区名称计算告警是否处于值班时段。",
                value_kind=ConfigValueKind.STRING,
                default="Asia/Shanghai",
                scopes=per_agent,
            ),
            ConfigDefinition(
                key="alerts.notification.on_call_weekdays",
                section="observability",
                label="告警值班工作日",
                description="值班工作日列表，使用 mon、tue、wed、thu、fri、sat、sun。",
                value_kind=ConfigValueKind.STRING_LIST,
                default=["mon", "tue", "wed", "thu", "fri"],
                scopes=per_agent,
            ),
            ConfigDefinition(
                key="alerts.notification.on_call_start_hour",
                section="observability",
                label="值班开始小时",
                description="值班时段的本地开始小时；与结束小时相同表示所选工作日全天值班。",
                value_kind=ConfigValueKind.INTEGER,
                default=9,
                scopes=per_agent,
                minimum=0,
                maximum=23,
            ),
            ConfigDefinition(
                key="alerts.notification.on_call_end_hour",
                section="observability",
                label="值班结束小时",
                description="值班时段的本地结束小时，允许小于开始小时以表示跨午夜。",
                value_kind=ConfigValueKind.INTEGER,
                default=18,
                scopes=per_agent,
                minimum=0,
                maximum=23,
            ),
            ConfigDefinition(
                key="alerts.notification.out_of_hours_adapter",
                section="observability",
                label="非值班通知适配器",
                description="非值班时段统一使用的通知适配器；默认表示继承主适配器。",
                value_kind=ConfigValueKind.STRING,
                default="default",
                scopes=per_agent,
                options=("default", *ALERT_NOTIFICATION_ADAPTERS),
            ),
            ConfigDefinition(
                key="alerts.notification.feishu_webhook_url",
                section="observability",
                label="飞书 Webhook 地址",
                description="飞书机器人告警 Webhook 地址，仅允许 HTTPS。",
                value_kind=ConfigValueKind.STRING,
                default="",
                scopes=per_agent,
            ),
            ConfigDefinition(
                key="alerts.notification.feishu_signing_secret",
                section="observability",
                label="飞书签名密钥",
                description="飞书 Webhook 签名 Secret，管理 API 永不回显明文。",
                value_kind=ConfigValueKind.SECRET,
                default=None,
                scopes=per_agent,
                secret=True,
            ),
            ConfigDefinition(
                key="alerts.notification.email.smtp_host",
                section="observability",
                label="邮件 SMTP 主机",
                description="告警邮件使用的 SMTP 服务主机。",
                value_kind=ConfigValueKind.STRING,
                default="",
                scopes=per_agent,
            ),
            ConfigDefinition(
                key="alerts.notification.email.smtp_port",
                section="observability",
                label="邮件 SMTP 端口",
                description="告警邮件使用的 SMTP 服务端口。",
                value_kind=ConfigValueKind.INTEGER,
                default=587,
                scopes=per_agent,
                minimum=1,
                maximum=65535,
            ),
            ConfigDefinition(
                key="alerts.notification.email.smtp_username",
                section="observability",
                label="邮件 SMTP 用户名",
                description="SMTP 登录用户名，可留空用于匿名投递。",
                value_kind=ConfigValueKind.STRING,
                default="",
                scopes=per_agent,
            ),
            ConfigDefinition(
                key="alerts.notification.email.from_address",
                section="observability",
                label="告警邮件发件人",
                description="告警邮件 From 地址。",
                value_kind=ConfigValueKind.STRING,
                default="",
                scopes=per_agent,
            ),
            ConfigDefinition(
                key="alerts.notification.email.recipient",
                section="observability",
                label="告警邮件收件人",
                description="告警邮件 To 地址。",
                value_kind=ConfigValueKind.STRING,
                default="",
                scopes=per_agent,
            ),
            ConfigDefinition(
                key="alerts.notification.email.smtp_tls",
                section="observability",
                label="启用 SMTP TLS",
                description="连接 SMTP 服务时启用 STARTTLS。",
                value_kind=ConfigValueKind.BOOLEAN,
                default=True,
                scopes=per_agent,
            ),
            ConfigDefinition(
                key="alerts.notification.email_password",
                section="observability",
                label="邮件 SMTP 密码",
                description="SMTP 登录密码，使用 SecretStore 加密保存。",
                value_kind=ConfigValueKind.SECRET,
                default=None,
                scopes=per_agent,
                secret=True,
            ),
            ConfigDefinition(
                key="alerts.notification.webhook_url",
                section="observability",
                label="告警 Webhook 地址",
                description="只允许 HTTPS 且不允许用户信息或内网目标的通知地址。",
                value_kind=ConfigValueKind.STRING,
                default="",
                scopes=per_agent,
            ),
            ConfigDefinition(
                key="alerts.notification.webhook_timeout_seconds",
                section="observability",
                label="告警 Webhook 超时",
                description="单次告警通知请求的超时秒数。",
                value_kind=ConfigValueKind.INTEGER,
                default=5,
                scopes=per_agent,
                minimum=1,
                maximum=30,
            ),
            ConfigDefinition(
                key="alerts.notification.webhook_max_retries",
                section="observability",
                label="告警 Webhook 最大重试",
                description="网络错误或 429/5xx 响应允许的重试次数。",
                value_kind=ConfigValueKind.INTEGER,
                default=2,
                scopes=per_agent,
                minimum=0,
                maximum=5,
            ),
            ConfigDefinition(
                key="alerts.notification.webhook_signing_secret",
                section="observability",
                label="告警 Webhook 签名密钥",
                description="用于 HMAC-SHA256 的 SecretStore 密钥，管理 API 永不回显明文。",
                value_kind=ConfigValueKind.SECRET,
                default=None,
                scopes=per_agent,
                secret=True,
            ),
            ConfigDefinition(
                key="cost.window_budget_usd",
                section="observability",
                label="模型成本窗口预算",
                description="当前聚合窗口冻结估算模型成本的美元预算上限。",
                value_kind=ConfigValueKind.NUMBER,
                default=5.0,
                scopes=system_and_tenant,
                minimum=0,
                maximum=1000000,
            ),
            ConfigDefinition(
                key="memory.recall.limit",
                section="memory",
                label="记忆召回数量",
                description="最终进入认知上下文的长期记忆条目上限。",
                value_kind=ConfigValueKind.INTEGER,
                default=12,
                scopes=per_agent,
                minimum=1,
                maximum=100,
            ),
            ConfigDefinition(
                key="memory.embedding.version",
                section="memory",
                label="记忆向量版本",
                description="长期记忆写入与召回使用的向量编码版本；切换后应执行渐进重建。",
                value_kind=ConfigValueKind.STRING,
                default="local-hash-v1",
                scopes=per_agent,
                options=("local-hash-v1",),
            ),
            ConfigDefinition(
                key="memory.recall.candidate_pool",
                section="memory",
                label="记忆候选池大小",
                description="全文、Trigram 与向量检索进入混合重排的最大候选数量。",
                value_kind=ConfigValueKind.INTEGER,
                default=60,
                scopes=per_agent,
                minimum=1,
                maximum=500,
            ),
            ConfigDefinition(
                key="memory.recall.recency_half_life_days",
                section="memory",
                label="记忆时间半衰期",
                description="时间相关性衰减到一半所需天数。",
                value_kind=ConfigValueKind.NUMBER,
                default=30.0,
                scopes=per_agent,
                minimum=0.1,
                maximum=3650,
            ),
            ConfigDefinition(
                key="memory.recall.maximum_sensitivity",
                section="memory",
                label="召回最高敏感级别",
                description="普通对话运行允许进入上下文的最高记忆敏感级别。",
                value_kind=ConfigValueKind.STRING,
                default="personal",
                scopes=per_agent,
                options=("normal", "personal", "sensitive", "restricted"),
            ),
            ConfigDefinition(
                key="memory.recall.full_text_weight",
                section="memory",
                label="全文相关权重",
                description="混合召回中全文和字符相似度的权重。",
                value_kind=ConfigValueKind.NUMBER,
                default=0.25,
                scopes=per_agent,
                minimum=0,
                maximum=1,
            ),
            ConfigDefinition(
                key="model.chat.max_output_tokens",
                section="model",
                label="对话输出 Token 上限",
                description="内部对话单次模型响应允许生成的最大 Token 数量。",
                value_kind=ConfigValueKind.INTEGER,
                default=1024,
                scopes=all_scopes,
                minimum=64,
                maximum=32768,
            ),
            ConfigDefinition(
                key="model.chat.total_token_budget",
                section="model",
                label="单次总 Token 预算",
                description="上下文估算与最大输出合计不得超过的单次运行预算。",
                value_kind=ConfigValueKind.INTEGER,
                default=26000,
                scopes=all_scopes,
                minimum=2048,
                maximum=240000,
            ),
            ConfigDefinition(
                key="model.chat.timeout_seconds",
                section="model",
                label="模型调用超时",
                description="单次模型流从建立到结束允许的最长秒数。",
                value_kind=ConfigValueKind.INTEGER,
                default=60,
                scopes=per_channel,
                minimum=5,
                maximum=600,
            ),
            ConfigDefinition(
                key="model.chat.max_attempts",
                section="model",
                label="模型最大尝试次数",
                description="仅在尚未输出文本时进行的有限尝试次数，避免流式内容重复。",
                value_kind=ConfigValueKind.INTEGER,
                default=2,
                scopes=per_channel,
                minimum=1,
                maximum=5,
            ),
            ConfigDefinition(
                key="model.chat.fallback_provider",
                section="model",
                label="降级模型服务",
                description="主路由在未输出内容且尝试失败后使用的安全降级模型服务。",
                value_kind=ConfigValueKind.STRING,
                default="development",
                scopes=per_channel,
                options=("development", "openai"),
            ),
            ConfigDefinition(
                key="model.chat.circuit_breaker_failures",
                section="model",
                label="熔断失败阈值",
                description="同一模型配置连续失败达到该次数后暂时停止调用。",
                value_kind=ConfigValueKind.INTEGER,
                default=3,
                scopes=per_channel,
                minimum=1,
                maximum=20,
            ),
            ConfigDefinition(
                key="model.chat.circuit_breaker_cooldown_seconds",
                section="model",
                label="熔断恢复时间",
                description="模型配置熔断后再次允许试探调用前等待的秒数。",
                value_kind=ConfigValueKind.INTEGER,
                default=30,
                scopes=per_channel,
                minimum=1,
                maximum=3600,
            ),
            ConfigDefinition(
                key="model.chat.provider",
                section="model",
                label="对话模型服务",
                description="对话运行使用的模型服务；开发模式无需外部凭证。",
                value_kind=ConfigValueKind.STRING,
                default="development",
                scopes=per_channel,
                options=("development", "openai"),
            ),
            ConfigDefinition(
                key="model.openai.api_key",
                section="model",
                label="OpenAI API 密钥",
                description="调用 OpenAI Responses API 的访问密钥，仅可写入、轮换和检查。",
                value_kind=ConfigValueKind.SECRET,
                default=None,
                scopes=per_agent,
                secret=True,
            ),
            ConfigDefinition(
                key="model.openai.model",
                section="model",
                label="OpenAI 对话模型",
                description="通过 OpenAI Responses API 调用的模型名称。",
                value_kind=ConfigValueKind.STRING,
                default="gpt-5-mini",
                scopes=per_channel,
            ),
            ConfigDefinition(
                key="memory.recall.semantic_weight",
                section="memory",
                label="语义相关权重",
                description="混合召回中语义相似度的初始权重。",
                value_kind=ConfigValueKind.NUMBER,
                default=0.35,
                scopes=per_agent,
                minimum=0,
                maximum=1,
            ),
            ConfigDefinition(
                key="memory.recall.recency_weight",
                section="memory",
                label="时间相关权重",
                description="混合召回中时间衰减分量的权重。",
                value_kind=ConfigValueKind.NUMBER,
                default=0.15,
                scopes=per_agent,
                minimum=0,
                maximum=1,
            ),
            ConfigDefinition(
                key="memory.recall.importance_weight",
                section="memory",
                label="重要性权重",
                description="混合召回中人工或反思标注意义强度的权重。",
                value_kind=ConfigValueKind.NUMBER,
                default=0.15,
                scopes=per_agent,
                minimum=0,
                maximum=1,
            ),
            ConfigDefinition(
                key="memory.recall.relationship_weight",
                section="memory",
                label="关系连续性权重",
                description="混合召回中当前用户关系熟悉度的权重。",
                value_kind=ConfigValueKind.NUMBER,
                default=0.10,
                scopes=per_agent,
                minimum=0,
                maximum=1,
            ),
            ConfigDefinition(
                key="proactive.enabled",
                section="proactive",
                label="允许主动行为",
                description="允许智能体创建主动联系候选；候选仍需通过策略门。",
                value_kind=ConfigValueKind.BOOLEAN,
                default=False,
                scopes=all_scopes,
            ),
            ConfigDefinition(
                key="proactive.minimum_score",
                section="proactive",
                label="主动行为最低评分",
                description="关系、时效、重要性和置信度的综合评分达到该值后才允许分发。",
                value_kind=ConfigValueKind.NUMBER,
                default=0.7,
                scopes=all_scopes,
                minimum=0,
                maximum=1,
            ),
            ConfigDefinition(
                key="proactive.quiet_hours_start",
                section="proactive",
                label="安静时段开始小时",
                description="按用户时区计算的 24 小时制开始小时。",
                value_kind=ConfigValueKind.INTEGER,
                default=22,
                scopes=all_scopes,
                minimum=0,
                maximum=23,
            ),
            ConfigDefinition(
                key="proactive.quiet_hours_end",
                section="proactive",
                label="安静时段结束小时",
                description="按用户时区计算的 24 小时制结束小时。",
                value_kind=ConfigValueKind.INTEGER,
                default=8,
                scopes=all_scopes,
                minimum=0,
                maximum=23,
            ),
            ConfigDefinition(
                key="proactive.require_recent_user_days",
                section="proactive",
                label="用户最近活跃天数",
                description="超过该天数没有用户主动互动时，禁止智能体主动联系。",
                value_kind=ConfigValueKind.INTEGER,
                default=30,
                scopes=all_scopes,
                minimum=1,
                maximum=365,
            ),
            ConfigDefinition(
                key="persona.system_prompt",
                section="persona",
                label="基础人格提示",
                description="进入对话模型的基础人格与行为边界；后续将迁移至独立人格版本。",
                value_kind=ConfigValueKind.STRING,
                default=(
                    "你是一个自然、友善且尊重边界的赛博网友。"
                    "请直接回应用户，不要声称执行了未发生的操作。"
                ),
                scopes=per_agent,
            ),
            ConfigDefinition(
                key="proactive.daily_message_budget",
                section="proactive",
                label="每日主动消息预算",
                description="单个智能体对单个用户每日可发送的主动消息上限。",
                value_kind=ConfigValueKind.INTEGER,
                default=2,
                scopes=all_scopes,
                minimum=0,
                maximum=20,
            ),
            ConfigDefinition(
                key="attachment.max_size_bytes",
                section="attachment",
                label="附件大小上限",
                description="单个附件允许上传的最大字节数，超出后服务端拒绝预签名申请。",
                value_kind=ConfigValueKind.INTEGER,
                default=25 * 1024 * 1024,
                scopes=per_agent,
                minimum=1,
                maximum=250 * 1024 * 1024,
            ),
            ConfigDefinition(
                key="attachment.allowed_mime_types",
                section="attachment",
                label="允许的附件类型",
                description="上传白名单；对象完成上传时仍会再次校验实际媒体类型。",
                value_kind=ConfigValueKind.STRING_LIST,
                default=[
                    "image/png",
                    "image/jpeg",
                    "image/webp",
                    "image/gif",
                    "text/plain",
                    "text/markdown",
                    "text/csv",
                    "application/json",
                    "application/pdf",
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                ],
                scopes=per_agent,
            ),
            ConfigDefinition(
                key="attachment.upload_expiry_seconds",
                section="attachment",
                label="上传授权有效期",
                description="预签名 PUT 授权的有效秒数，过期的待上传对象可被清理任务回收。",
                value_kind=ConfigValueKind.INTEGER,
                default=900,
                scopes=per_agent,
                minimum=60,
                maximum=3600,
            ),
            ConfigDefinition(
                key="model.multimodal.max_image_bytes",
                section="multimodal",
                label="单张模型图片上限",
                description="图片从 MinIO 读取并发送给模型前允许的最大字节数；超限时改为文本说明。",
                value_kind=ConfigValueKind.INTEGER,
                default=5 * 1024 * 1024,
                scopes=per_agent,
                minimum=64 * 1024,
                maximum=25 * 1024 * 1024,
            ),
            ConfigDefinition(
                key="model.multimodal.max_document_bytes",
                section="multimodal",
                label="单个模型文档上限",
                description="文档从 MinIO 读取、提取正文并发送给模型前允许的最大字节数。",
                value_kind=ConfigValueKind.INTEGER,
                default=10 * 1024 * 1024,
                scopes=per_agent,
                minimum=64 * 1024,
                maximum=25 * 1024 * 1024,
            ),
            ConfigDefinition(
                key="model.multimodal.max_total_bytes",
                section="multimodal",
                label="单次模型附件总量",
                description="一次模型请求可从私有桶读取的全部图片和文档字节总量。",
                value_kind=ConfigValueKind.INTEGER,
                default=20 * 1024 * 1024,
                scopes=per_agent,
                minimum=64 * 1024,
                maximum=50 * 1024 * 1024,
            ),
            ConfigDefinition(
                key="model.multimodal.max_document_characters",
                section="multimodal",
                label="文档正文字符上限",
                description="单个文档用于能力降级和上下文预算估算的最大正文字符数。",
                value_kind=ConfigValueKind.INTEGER,
                default=100_000,
                scopes=per_agent,
                minimum=1_000,
                maximum=1_000_000,
            ),
            ConfigDefinition(
                key="model.multimodal.max_pdf_pages",
                section="multimodal",
                label="PDF 正文提取页数",
                description="单个 PDF 最多提取的页面数；原始文件仍受模型和字节限制约束。",
                value_kind=ConfigValueKind.INTEGER,
                default=50,
                scopes=per_agent,
                minimum=1,
                maximum=500,
            ),
            ConfigDefinition(
                key="data.retention.deleted_agent_days",
                section="data_lifecycle",
                label="已删除智能体保留天数",
                description="软删除智能体及其全部关联数据进入物理清理流程前保留的天数。",
                value_kind=ConfigValueKind.INTEGER,
                default=30,
                scopes=system_and_tenant,
                minimum=1,
                maximum=3650,
            ),
            ConfigDefinition(
                key="data.retention.deleted_conversation_days",
                section="data_lifecycle",
                label="已删除会话保留天数",
                description="软删除会话在最终删除数据库记录与私有对象前保留的天数。",
                value_kind=ConfigValueKind.INTEGER,
                default=30,
                scopes=all_scopes,
                minimum=1,
                maximum=3650,
            ),
            ConfigDefinition(
                key="data.retention.deleted_attachment_days",
                section="data_lifecycle",
                label="已删除附件元数据保留天数",
                description="对象已删除后，最小附件审计元数据继续保留的天数。",
                value_kind=ConfigValueKind.INTEGER,
                default=7,
                scopes=all_scopes,
                minimum=1,
                maximum=3650,
            ),
            ConfigDefinition(
                key="data.retention.observability_disposition_event_days",
                section="data_lifecycle",
                label="告警处置事件保留天数",
                description="通用告警处置追加事件进入物理清理流程前保留的天数。",
                value_kind=ConfigValueKind.INTEGER,
                default=90,
                scopes=system_and_tenant,
                minimum=1,
                maximum=3650,
            ),
            ConfigDefinition(
                key="data.retention.observability_replay_review_days",
                section="data_lifecycle",
                label="告警重放复核保留天数",
                description="通用告警通知重放复核事件进入物理清理流程前保留的天数。",
                value_kind=ConfigValueKind.INTEGER,
                default=90,
                scopes=system_and_tenant,
                minimum=1,
                maximum=3650,
            ),
            ConfigDefinition(
                key="data.retention.observability_recommendation_feedback_days",
                section="data_lifecycle",
                label="告警建议反馈保留天数",
                description="告警建议人工反馈进入物理清理流程前保留的天数。",
                value_kind=ConfigValueKind.INTEGER,
                default=90,
                scopes=system_and_tenant,
                minimum=1,
                maximum=3650,
            ),
            ConfigDefinition(
                key="data.retention.orphan_grace_hours",
                section="data_lifecycle",
                label="MinIO 孤儿宽限小时",
                description="没有数据库引用的对象必须超过该时长后才允许清理，避免误删在途上传。",
                value_kind=ConfigValueKind.INTEGER,
                default=24,
                scopes=all_scopes,
                minimum=1,
                maximum=720,
            ),
            ConfigDefinition(
                key="data.retention.batch_size",
                section="data_lifecycle",
                label="单次清理批量",
                description="保留期与孤儿清理单次最多处理的资源数量。",
                value_kind=ConfigValueKind.INTEGER,
                default=100,
                scopes=all_scopes,
                minimum=1,
                maximum=1000,
            ),
            ConfigDefinition(
                key="data.export.max_records",
                section="data_lifecycle",
                label="单次导出记录上限",
                description="用户数据导出最多包含的白名单记录数量，超过后拒绝并要求缩小范围。",
                value_kind=ConfigValueKind.INTEGER,
                default=10000,
                scopes=all_scopes,
                minimum=100,
                maximum=100000,
            ),
            ConfigDefinition(
                key="data.export.max_bytes",
                section="data_lifecycle",
                label="单次导出字节上限",
                description="同步 JSON 数据导出的最大字节数，防止管理请求耗尽内存。",
                value_kind=ConfigValueKind.INTEGER,
                default=25 * 1024 * 1024,
                scopes=all_scopes,
                minimum=1024 * 1024,
                maximum=100 * 1024 * 1024,
            ),
            ConfigDefinition(
                key="data.backup.expected_interval_hours",
                section="data_lifecycle",
                label="备份演练期望间隔",
                description="管理后台用于判断最近一次隔离恢复演练是否过期的小时数。",
                value_kind=ConfigValueKind.INTEGER,
                default=24 * 30,
                scopes=all_scopes,
                minimum=1,
                maximum=24 * 365,
            ),
            ConfigDefinition(
                key="channel.feishu.bot_credential",
                section="channel",
                label="飞书机器人凭证",
                description="飞书适配器使用的不透明凭证；当前占位实现只保存和检测配置状态。",
                value_kind=ConfigValueKind.SECRET,
                default=None,
                scopes=(ConfigScope.CHANNEL,),
                secret=True,
            ),
            ConfigDefinition(
                key="channel.discord.bot_token",
                section="channel",
                label="Discord Bot Token",
                description="Discord 适配器使用的不透明令牌；当前占位实现不会访问外部 API。",
                value_kind=ConfigValueKind.SECRET,
                default=None,
                scopes=(ConfigScope.CHANNEL,),
                secret=True,
            ),
            ConfigDefinition(
                key="channel.telegram.bot_token",
                section="channel",
                label="Telegram Bot Token",
                description=(
                    "Telegram 正式出站适配器使用的机器人令牌；只写入加密存储，"
                    "不通过 API、日志或诊断回显。"
                ),
                value_kind=ConfigValueKind.SECRET,
                default=None,
                scopes=(ConfigScope.CHANNEL,),
                secret=True,
            ),
            ConfigDefinition(
                key="channel.connection_probe_interval_minutes",
                section="channel",
                label="渠道连接探测间隔",
                description="启用渠道自动连接探测的最小间隔；Worker 按该间隔创建安全探测任务。",
                value_kind=ConfigValueKind.INTEGER,
                default=15,
                scopes=(ConfigScope.CHANNEL,),
                minimum=1,
                maximum=1440,
            ),
            ConfigDefinition(
                key="telegram_webhook_secret",
                section="channel",
                label="Telegram Webhook Secret",
                description=(
                    "Telegram 入站 Webhook 的请求头密钥；仅写入加密存储，"
                    "不会通过 API、日志、诊断或导出回显。"
                ),
                value_kind=ConfigValueKind.SECRET,
                default=None,
                scopes=(ConfigScope.CHANNEL,),
                secret=True,
            ),
        )
    )
