"""渠道 Adapter 协议、能力协商、正式实现与 IM 占位实现。"""

from cnb_adapters.alert_webhook import (
    AlertWebhookDeliveryResult,
    AlertWebhookError,
    AlertWebhookNotifier,
    AlertWebhookValidationError,
    validate_webhook_url,
)
from cnb_adapters.channel import (
    SAFE_ATTACHMENT_CONTENT_TYPES,
    SAFE_DOCUMENT_CONTENT_TYPES,
    SAFE_IMAGE_CONTENT_TYPES,
    AdapterDeliveryResult,
    AdapterHealth,
    CapabilityNegotiation,
    ChannelAdapter,
    ChannelAdapterError,
    ChannelCapabilityError,
    ChannelDeliveryCommand,
    ChannelInboundEvent,
    ChannelNotConfiguredError,
    ChannelRateLimitError,
    WebhookInfo,
    negotiate_capabilities,
    summarize_blocks,
)
from cnb_adapters.notification import (
    EmailNotificationAdapter,
    EmailTransport,
    FeishuWebhookNotificationAdapter,
    HttpsWebhookNotificationAdapter,
    NotificationAdapter,
    NotificationAdapterError,
    NotificationAdapterRegistry,
    NotificationAdapterValidationError,
    NotificationDeliveryCommand,
    NotificationDeliveryResult,
    SmtpEmailTransport,
    build_default_notification_registry,
)
from cnb_adapters.placeholder import PlaceholderAdapter
from cnb_adapters.registry import ChannelAdapterRegistry, build_default_channel_registry
from cnb_adapters.telegram import TelegramChannelAdapter, TelegramTransport
from cnb_adapters.web import WebChannelAdapter
from cnb_domain import ChannelCapabilities

__all__ = [
    "SAFE_ATTACHMENT_CONTENT_TYPES",
    "SAFE_DOCUMENT_CONTENT_TYPES",
    "SAFE_IMAGE_CONTENT_TYPES",
    "AdapterDeliveryResult",
    "AdapterHealth",
    "AlertWebhookDeliveryResult",
    "AlertWebhookError",
    "AlertWebhookNotifier",
    "AlertWebhookValidationError",
    "CapabilityNegotiation",
    "ChannelAdapter",
    "ChannelAdapterError",
    "ChannelAdapterRegistry",
    "ChannelCapabilities",
    "ChannelCapabilityError",
    "ChannelDeliveryCommand",
    "ChannelInboundEvent",
    "ChannelNotConfiguredError",
    "ChannelRateLimitError",
    "EmailNotificationAdapter",
    "EmailTransport",
    "FeishuWebhookNotificationAdapter",
    "HttpsWebhookNotificationAdapter",
    "NotificationAdapter",
    "NotificationAdapterError",
    "NotificationAdapterRegistry",
    "NotificationAdapterValidationError",
    "NotificationDeliveryCommand",
    "NotificationDeliveryResult",
    "PlaceholderAdapter",
    "SmtpEmailTransport",
    "TelegramChannelAdapter",
    "TelegramTransport",
    "WebChannelAdapter",
    "WebhookInfo",
    "build_default_channel_registry",
    "build_default_notification_registry",
    "negotiate_capabilities",
    "summarize_blocks",
    "validate_webhook_url",
]
